#! /bin/bash


#1) Execute the pwd command to check your location in the directory tree. Run the lscommand with appropriate switches to show files in the current directory along with ALL HIDDEN FILES. Redirect this command result to this file /tmp/content.txt
# Solution:  Using below commands task is successfully completed.
# ls -la >> /tmp/content.txt

#2) a)Log on to ec2 as ubuntu and execute the logname, whoami, who, and w commands one at a time. Verify the identity of ubuntu by comparing the output of these commands. The output should show ubuntu as the user logged on and running these commands. b)Execute the id and groups commands and verify the identity of ubuntu by comparing the output of these commands. Identify the additional information that the id command provides but not the groups command. c)Record your results in a text file created with the vi editor in ubuntu’s home directory.
# Solution:
# a)
#commands: logname ; whoami ; who ; w
#result: 
#ubuntu
#ubuntu
#ubuntu   pts/0        2021-09-16 22:15 (3.126.121.35)
# 22:53:17 up 2 days,  8:07,  1 user,  load average: 0.00, 0.00, 0.00
# USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
# ubuntu   pts/0    3.126.121.35     22:15    0.00s  0.09s  0.00s w
# b)
#command: id
#result:  uid=1000(ubuntu) gid=1000(ubuntu) groups=1000(ubuntu),119(docker)

#command: group
#result:  ubuntu docker

# c)
# logname >> task2_results.txt
# whoami >> task2_results.txt
# who >> task2_results.txt
# w >> task2_results.txt
# id >> task2_results.txt
# groups >> task2_results.txt


# 3) Log on to ec2 as root, execute the last and lastb commands, and record in a file which users have recently logged in to and out of the system successfully and unsuccessfully. Also list the timestamp when the system was last rebooted. Use the vi editor to record your results.

#4) Log on to ec2 as ubuntu and execute the hostname and uname commands. Identify the system’s name, kernel version, RHEL release, and the hardware architecture of this system. Record your results in a file using the vi editor.

#5) Log on to ec2 as ubuntu and execute the date and timedatectl commands to check the current system date and time. Identify the differences between the two outputs. Use timedatectl and change the system date to a date in January of the following year. Issue the date command and change the system time to one hour ahead of the current time. Observe the new date and time with both commands. Reset the date and time back to the current actual time using either the date or the timedatectl command.

#6) Log on to ec2 as ubuntu and execute the uptime command. Identify the amount of time the system has been up for and the number of users currently logged on. Run the wc command and show how many lines, words, and bytes are in the /etc/profile file.

#7) Log on to ec2 as ubuntu and execute the tar command to archive the contents of the entire /etc directory tree. List content of the tar archive  to the file. Restore the archive file to the /opt directory
