#! /bin/bash

# Here we can see some commands output: logname, whoami, who, w, id, groups
ubuntu
ubuntu
ubuntu   pts/0        2021-09-16 15:57 (3.68.106.162)
 18:29:01 up 2 days,  3:43,  1 user,  load average: 0.00, 0.00, 0.00
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
ubuntu   pts/0    3.68.106.162     15:57    5.00s  0.23s  0.00s w
uid=1000(ubuntu) gid=1000(ubuntu) groups=1000(ubuntu),119(docker)
ubuntu docker
